import {
    Button,
    Cell,
    CellGroup,
    Col,
    Dialog,
    Divider,
    Empty,
    Field,
    Form,
    GoodsAction,
    GoodsActionButton,
    GoodsActionIcon,
    Grid,
    GridItem,
    Icon,
    Image,
    Lazyload,
    Loading,
    NavBar,
    NumberKeyboard,
    PasswordInput,
    Picker,
    Popup,
    Radio,
    RadioGroup,
    Row,
    Search,
    Switch,
    Tabbar,
    TabbarItem,
    Tag,
    Toast,
    Uploader
} from 'vant'
import Vue from 'vue'

Vue.use(Col)
Vue.use(Button)
Vue.use(Image)
Vue.use(Loading)
Vue.use(Row)
Vue.use(Search)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Toast)
Vue.use(Empty)
Vue.use(Icon)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(CellGroup)
Vue.use(Cell)
Vue.use(Popup)
Vue.use(Picker)
Vue.use(Uploader)
Vue.use(Tag)
Vue.use(Switch)
Vue.use(Dialog)
Vue.use(Lazyload)
Vue.use(GoodsAction)
Vue.use(GoodsActionIcon)
Vue.use(GoodsActionButton)
Vue.use(Divider)
Vue.use(PasswordInput)
Vue.use(NumberKeyboard)
Vue.use(Radio)
Vue.use(RadioGroup)